server {
  listen 80;
  server_name _;
  absolute_redirect off;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /ynov-cicd/;
  }

  location = /ynov-cicd {
    return 302 /ynov-cicd/;
  }

  location /ynov-cicd/ {
    try_files $uri $uri/ /ynov-cicd/index.html;
  }
}
