server {
  listen 80;
  server_name _;
  absolute_redirect off;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /ynov-cicd/;
  }

  location = /ynov-cicd {
    return 301 /ynov-cicd/;
  }

  location /ynov-cicd/ {
    try_files $uri /ynov-cicd/index.html;
  }

  location /api/ {
    proxy_pass http://backend:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
